export type GhostViewStatus = 'ready' | 'offline'
export type GhostProvider = 'ollama' | 'mlx-vlm' | 'openai-compatible' | 'opencode'
export type GhostAutoAcceptScope = 'confirm' | 'one-edit' | 'current-file' | 'request' | 'session' | 'workspace' | 'always'
export type GhostMode = 'ask' | 'edit' | 'agent' | 'plan' | 'explain' | 'inline'
export type GhostResponseLength = 'short' | 'balanced' | 'long' | 'unlimited'
export type GhostLogLevel = 'off' | 'error' | 'warn' | 'info' | 'debug'
export type GhostModelRole = 'chat' | 'agent' | 'vision' | 'autocomplete'
export type GhostRequestStatus =
  | 'idle'
  | 'preparing'
  | 'connecting'
  | 'thinking'
  | 'streaming'
  | 'waiting-for-approval'
  | 'completed'
  | 'cancelled'
  | 'failed'
export type GhostProgressPhase = 'context' | 'provider' | 'thinking' | 'streaming' | 'tool' | 'complete' | 'error'
export type GhostStopReason =
  | 'failed-tool'
  | 'invalid-model-response'
  | 'cancelled'
  | 'timeout'
  | 'approval-rejected'
  | 'context-limit'
  | 'budget-limit'
  | 'provider-failure'

export type GhostToolName =
  | 'ghost_read_file'
  | 'ghost_search_workspace'
  | 'ghost_get_diagnostics'
  | 'ghost_git_context'
  | 'ghost_update_task_plan'
  | 'ghost_record_completion'
  | 'ghost_write_file'
  | 'ghost_apply_edit'
  | 'ghost_apply_transaction'
  | 'ghost_run_terminal_command'
  | 'ghost_list_directory'
